In [1]:
import pandas as pd
import numpy as np

In [2]:
url='https://github.com/prasertcbs/basic-dataset/raw/master/ISLR/Advertising.csv'
df=pd.read_csv(url, usecols=[1,2,3,4])
df

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

## sklearn : train_test_split

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
len(df)

200

### method 1: split into (train, test)

In [5]:
train, test = train_test_split(df, train_size=.7, random_state=7)

In [6]:
print(len(train))
print(len(test))

140
60


In [7]:
train.head()

TV  Radio  Newspaper  Sales
88    88.3   25.5       73.4   12.9
58   210.8   49.6       37.7   23.8
113  209.6   20.6       10.7   15.9
149   44.7   25.8       20.6   10.1
36   266.9   43.8        5.0   25.4

In [8]:
test.head()

TV  Radio  Newspaper  Sales
86    76.3   27.5       16.0   12.0
120  141.3   26.8       46.2   15.5
22    13.2   15.9       49.6    5.6
11   214.7   24.0        4.0   17.4
195   38.2    3.7       13.8    7.6

### method 2: split into (X_train, X_test, y_train, y_test)

In [9]:
df.columns

Index(['TV', 'Radio', 'Newspaper', 'Sales'], dtype='object')

In [10]:
X = df[['TV', 'Radio', 'Newspaper']]
y = df['Sales']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=.3,random_state=7)

In [12]:
X_train.head()

TV  Radio  Newspaper
88    88.3   25.5       73.4
58   210.8   49.6       37.7
113  209.6   20.6       10.7
149   44.7   25.8       20.6
36   266.9   43.8        5.0

In [13]:
X_test

TV  Radio  Newspaper
86    76.3   27.5       16.0
120  141.3   26.8       46.2
22    13.2   15.9       49.6
11   214.7   24.0        4.0
195   38.2    3.7       13.8
2     17.2   45.9       69.3
121   18.8   21.7       50.4
94   107.4   14.0       10.9
66    31.5   24.6        2.2
63   102.7   29.6        8.4
108   13.1    0.4       25.6
96   197.6    3.5        5.9
138   43.0   25.9       20.5
65    69.0    9.3        0.9
188  286.0   13.9        3.7
155    4.1   11.6        5.7
24    62.3   12.6       18.3
99   135.2   41.7       45.9
153  171.3   39.7       37.7
46    89.7    9.9       35.7
178  276.7    2.3       23.7
139  184.9   43.9        1.7
143  104.6    5.7       34.4
74   213.4   24.6       13.1
186  139.5    2.1       26.6
169  284.3   10.6        6.4
101  296.4   36.3      100.9
197  177.0    9.3        6.4
109  255.4   26.9        5.5
177  170.2    7.8       35.2
57   136.2   19.2       16.6
106   25.0   11.0       29.7
160  172.5   18.1       30.7
84   213.5   43.0       33.8
124  229.5   32.3       74.2
85   193.2   18.4       65.7
126    7.8   38.9       50.6
183  287.6   43.0       71.8
80    76.4   26.7       22.3
116  139.2   14.3       25.6
129   59.6   12.0       43.1
128  220.3   49.0        3.2
60    53.5    2.0       21.4
122  224.0    2.4       15.6
27   240.1   16.7       22.9
40   202.5   22.3       31.6
45   175.1   22.5       31.5
191   75.5   10.8        6.0
31   112.9   17.4       38.6
154  187.8   21.1        9.5
32    97.2    1.5       30.0
13    97.5    7.6        7.2
117   76.4    0.8       14.8
78     5.4   29.9        9.4
131  265.2    2.9       43.0
28   248.8   27.1       22.9
18    69.2   20.5       18.3
141  193.7   35.4       75.6
134   36.9   38.6       65.6
97   184.9   21.0       22.0

In [15]:
y_train

88     12.9
58     23.8
113    15.9
149    10.1
36     25.4
       ... 
151    11.6
67     13.4
25     12.0
196     9.7
175    27.0
Name: Sales, Length: 140, dtype: float64

In [16]:
y_test

86     12.0
120    15.5
22      5.6
11     17.4
195     7.6
2       9.3
121     7.0
94     11.5
66      9.5
63     14.0
108     5.3
96     11.7
138     9.6
65      9.3
188    15.9
155     3.2
24      9.7
99     17.2
153    19.0
46     10.6
178    11.8
139    20.7
143    10.4
74     17.0
186    10.3
169    15.0
101    23.8
197    12.8
109    19.8
177    11.7
57     13.2
106     7.2
160    14.4
84     21.7
124    19.7
85     15.2
126     6.6
183    26.2
80     11.8
116    12.2
129     9.7
128    24.7
60      8.1
122    11.6
27     15.9
40     16.6
45     14.9
191     9.9
31     11.9
154    15.6
32      9.6
13      9.7
117     9.4
78      5.3
131    12.7
28     18.9
18     11.3
141    19.2
134    10.8
97     15.5
Name: Sales, dtype: float64

## LinearRegression

In [17]:
from sklearn.linear_model import LinearRegression

In [19]:
model = LinearRegression()
model

LinearRegression()

In [20]:
model.fit(X_train, y_train)

LinearRegression()

In [22]:
model.score(X_train,y_train)

0.8970470429900155

In [23]:
model.intercept_

2.597191399021309

In [24]:
model.coef_

array([ 4.71259657e-02,  1.90987993e-01, -1.93812266e-05])

In [25]:
model.predict([[200,40,70]])

C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([19.66054756])

In [26]:
model.predict([[200,40,70],
               [100,80,50],
               [ 40,20,10]])

C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([19.66054756, 22.58785835,  8.30179607])

In [27]:
y_hat = model.predict(X_train)
y_hat

array([11.62718541, 22.00361874, 16.40893908,  9.63081303, 23.54028882,
        4.19019633,  6.33372661,  9.16205331, 18.6252243 ,  9.30278314,
       10.02220298, 12.81990978, 16.3270569 , 15.55142217,  8.18788222,
       17.73045095, 24.32738343,  7.98376479, 12.34504657, 23.42048119,
       10.19514611, 17.25432468, 15.17745615, 16.45100472, 16.83421976,
       16.94913148, 14.92719588, 12.08456358, 17.31673623, 20.75868218,
       12.31079013, 14.68033357, 12.00487231,  4.23083643, 11.88897069,
       18.47946596, 17.82345369, 10.62147609, 21.24463139,  3.40353011,
       20.37338186,  9.53396325,  8.95973195, 10.92777341,  8.97930171,
       17.62344551, 20.54153871, 12.60435152, 13.71875285, 17.33050151,
       15.22001133, 20.47732861,  9.86186951, 14.93210984, 13.95134117,
       12.31718956, 16.32085396,  7.16859379, 18.16059791, 20.91470709,
       20.02490033, 18.17883475, 18.49821442, 17.0839661 , 19.35270232,
        4.19833505, 12.50911724, 17.95656145,  6.91422545,  9.90

## Statsmodels: Simple Linear Regression

In [28]:
train, test = train_test_split(df, train_size=.7, random_state=7)

In [29]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [30]:
model_a=smf.ols(formula='Sales ~ TV + Radio + Newspaper', data=train).fit()

In [31]:
print(model_a.summary())

                            OLS Regression Results                            
Dep. Variable:                  Sales   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.895
Method:                 Least Squares   F-statistic:                     395.0
Date:                Mon, 21 Nov 2022   Prob (F-statistic):           6.42e-67
Time:                        17:02:24   Log-Likelihood:                -271.78
No. Observations:                 140   AIC:                             551.6
Df Residuals:                     136   BIC:                             563.3
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.5972      0.398      6.533      0.0

In [32]:
model_a.params

Intercept    2.597191
TV           0.047126
Radio        0.190988
Newspaper   -0.000019
dtype: float64

In [33]:
model_a.pvalues

Intercept    1.189005e-09
TV           1.024402e-57
Radio        7.808066e-40
Newspaper    9.978470e-01
dtype: float64

In [34]:
model.intercept_

2.597191399021309

In [35]:
model.coef_

array([ 4.71259657e-02,  1.90987993e-01, -1.93812266e-05])